#!/bin/sh
#
# Convencience wrapper for vnc over ssh tunnel

PORT=5900
BIND=localhost

if [ -z "$1" ]; then
	echo "Usage: $0 host" 1>&2
	exit 1
fi

SSH="ssh $1 -fNL $PORT:$BIND:$PORT"
$SSH

swaymsg mode '$mode_vnc'
wlvncc -e tight $BIND $PORT&
CHLD="$!"

echo CHILDREN "$CHLD"

cleanup() {
	swaymsg mode default
	kill $CHLD 2>/dev/null
	pkill -f "$SSH"
}

trap 'cleanup' INT TERM EXIT

wait
